server:
  port: 8080
  error:
    whitelabel:
      enabled: false

resilience4j:
  circuitbreaker:
    instances:
      metadataCircuitBreaker:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      metadataCircuitBreaker:
        timeout-duration: 3s
        cancel-running-future: true

spring:
  application:
    name: ApiGateway
  profiles:
    active: dev
  webflux:
    base-path: /
  cloud:
    gateway:
      routes:
        # Thay vì http://localhost:8081, ta dùng lb:// cộng với TÊN SERVICE đăng ký trên Eureka
        
        # Service để test (Echo)
        - id: dummy-echo-service
          uri: lb://DUMMY-ECHO-SERVICE
          predicates:
            - Path=/api/internal/**
          filters:
            - RewritePath=/api/internal/(?<segment>.*), /internal/${segment}

        # Auth service
        - id: csfc-auth-serviceaa
          uri: lb://CSFC-AUTH-SERVICE
          predicates:
            - Path=/api/auth-service/**
          filters:
            - RewritePath=/api/auth-service/(?<segment>.*), /auth/${segment}

        - id: franchise-contract-service
          uri: lb://FRANCHISESERVICE
          predicates:
            - Path=/api/contracts/**
          filters:
            - RewritePath=/api/contracts/(?<segment>.*), /api/contracts/${segment}
  
        # ========= METADATA =========
        - id: metadata-service
          uri: lb://METADATA-SERVICE
          predicates:
            - Path=/api/metadata/**
          filters:
            - RewritePath=/api/metadata/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: metadataCircuitBreaker
                fallbackUri: forward:/fallback/METADATA-SERVICE

     # Ví dụ sẵn cho các service sau này của bạn
        # - id: franchise-service
        #   uri: lb://FRANCHISE-SERVICE
        #   predicates:
        #     - Path=/api/franchises/**


app:
  version: 1.0.0

security:
  jwt:
    secret: ${JWT_SECRET:V7Pz0c5ZmTz4IVBdBrgiapaNOSKpRDWtT8AsXm+C1mE=}

# --- CẤU HÌNH EUREKA CLIENT ---
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  endpoint:
    health:
      show-details: always

rate-limit:
  ip:
    enabled: true
    config-key: gateway.ip.rate_limit.per_minute
    default-limit: 60
    window-seconds: 60
    refresh-seconds: 15

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name:}] [requestId:%X{requestId}] %logger - %msg%n"