spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: metadata-service
          uri: http://localhost:${wiremock.server.port}
          predicates:
            - Path=/api/metadata/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: metadataCircuitBreaker

eureka:
  client:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      metadataCircuitBreaker:
        sliding-window-size: 5
        failure-rate-threshold: 50
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 10s
  timelimiter:
    instances:
      metadataCircuitBreaker:
        timeout-duration: 2s