server:
  address: 0.0.0.0
  port: ${PORT:8763}

spring:
  application:
    name: metadata-service

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      url: redis://default:ItRBEjljWMXDHICNFJdCxBTjGIHPmzMk@centerbeam.proxy.rlwy.net:25969

  cache:
    type: none

  datasource:
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:39756/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:pNXyuMURcClGkORjMGPzkfZezcuwjhkj}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://microservice-i7nc.onrender.com/eureka/}
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 10

  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    secure-port: 443
    secure-port-enabled: true
    non-secure-port-enabled: false
    status-page-url: https://${RENDER_EXTERNAL_HOSTNAME:localhost}/actuator/info
    health-check-url: https://${RENDER_EXTERNAL_HOSTNAME:localhost}/actuator/health
    home-page-url: https://${RENDER_EXTERNAL_HOSTNAME:localhost}/
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${RENDER_EXTERNAL_HOSTNAME:localhost}

auth:
  service:
    url: ${AUTH_SERVICE_URL:https://api-gate-way.onrender.com}

rbp:
  config: ${RBP_CONFIG:}

metadata:
  key:
    pattern: "^[a-zA-Z_][a-zA-Z0-9_.]*$"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true