spring.application.name=warehouse-service
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=warehouseDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
aws.region: ap-southeast-1
aws.s3.bucket-name: warehousefr
server.port=8084