spring.application.name=discovery-service
server.port=${PORT:8761}

# Không để Eureka Server tự đăng ký chính nó
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:false}

# URL của Eureka Server
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

# Cấu hình instance
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# THEM 2 DONG NAY
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
